// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmQM4RGgbmwNQQxAq7uHtgGQfFrRuk7NQ',
    appId: '1:489821187729:web:6d9c339b1cd5fe204ed930',
    messagingSenderId: '489821187729',
    projectId: 'cozy-room-52b00',
    authDomain: 'cozy-room-52b00.firebaseapp.com',
    storageBucket: 'cozy-room-52b00.firebasestorage.app',
    measurementId: 'G-BSV7XVRFRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3KzAyQlo14LPgectEx6diEreX1_IEHv0',
    appId: '1:489821187729:android:14497f5734776fb74ed930',
    messagingSenderId: '489821187729',
    projectId: 'cozy-room-52b00',
    storageBucket: 'cozy-room-52b00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMBTguLdWBihM1ELXgNIb2enxFyu_cX-8',
    appId: '1:489821187729:ios:97b3e76c891e88ff4ed930',
    messagingSenderId: '489821187729',
    projectId: 'cozy-room-52b00',
    storageBucket: 'cozy-room-52b00.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMBTguLdWBihM1ELXgNIb2enxFyu_cX-8',
    appId: '1:489821187729:ios:97b3e76c891e88ff4ed930',
    messagingSenderId: '489821187729',
    projectId: 'cozy-room-52b00',
    storageBucket: 'cozy-room-52b00.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmQM4RGgbmwNQQxAq7uHtgGQfFrRuk7NQ',
    appId: '1:489821187729:web:e57c9b0e5f8cbfc14ed930',
    messagingSenderId: '489821187729',
    projectId: 'cozy-room-52b00',
    authDomain: 'cozy-room-52b00.firebaseapp.com',
    storageBucket: 'cozy-room-52b00.firebasestorage.app',
    measurementId: 'G-92MFEXV4MN',
  );
}
